# Hyperparameters for training

##box: 0.05  # box loss gain 本来是3.54
##cls: 0.5  # cls loss gain 本来是37.4
##obj: 1.0  # obj loss gain (scale with pixels) # 本来是64.3
#ciou: 1.0
box: 3.54
cls: 37.4
obj: 64.3
cls_pw: 1.0  # cls BCELoss positive_weight
obj_pw: 1.0  # obj BCELoss positive_weight
iou_t: 0.20  # IoU training threshold
anchor_t: 4.0  # anchor-multiple threshold

lr0: 0.0008  # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.1  # final OneCycleLR learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
weight_decay: 0.0005  # optimizer weight decay 5e-4

fl_gamma: 0.0  # focal loss gamma (efficientDet default is gamma=1.5)
hsv_h: 0.0138  # image HSV-Hue augmentation (fraction)
hsv_s: 0.678  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.36  # image HSV-Value augmentation (fraction)
degrees: 0  # image rotation (+/- deg)
translate: 0  # image translation (+/- fraction)
scale: 0  # image scale (+/- gain)
shear: 0  # image shear (+/- deg)